[package]
name = "signal_processing"
version = "0.3.0"
edition = "2024"
license = "MIT"
description = "A signal processing library."
repository = "https://github.com/sigurd4/signal_processing"
keywords = ["signal_processing", "dsp", "dtsp", "filters", "filter-design"]
authors = ["Sigurd Sætherø Spangelo"]
categories = ["computer-vision", "algorithms", "mathematics", "multimedia", "science"]
exclude = ["/plots", "/images", "/temp"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "2.0.17"
moddef = "0.3.0"
num = "0.4.3"
rand = "0.9.2"
ndarray = "0.17.1"
ndarray-linalg = {version = "0.18.0", features = ["intel-mkl"]}
statrs = "0.18.0"
bulks = "0.2.0"
array_trait = {version = "*", default-features = false, features = ["length"]}

[dev-dependencies]
plotters = "0.3.5"
linspace = "0.2.3"
image = "0.25.8"