[package]
name = "signal_fir_design"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = {workspace = true}
num-complex = {workspace = true}
bulks = {workspace = true}
signal_windows = {workspace = true}
array_trait = {workspace = true}